# Generated by Django 4.1 on 2022-08-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('idcompania', models.AutoField(db_column='idCompania', primary_key=True, serialize=False)),
                ('nombrecompania', models.CharField(blank=True, db_column='nombreCompania', max_length=45, null=True)),
                ('ruc', models.CharField(blank=True, max_length=45, null=True)),
                ('nombrecoordinador', models.CharField(blank=True, db_column='nombreCoordinador', max_length=45, null=True)),
                ('celular', models.CharField(blank=True, max_length=45, null=True)),
                ('correo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'compania',
                'managed': False,
            },
        ),
    ]
